"""gender column

Revision ID: 17826a79aeba
Revises: 648bdf62c7e8
Create Date: 2021-09-18 19:10:11.926194

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17826a79aeba'
down_revision = '648bdf62c7e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('gender', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'gender')
    # ### end Alembic commands ###
