"""avatar column

Revision ID: 648bdf62c7e8
Revises: 742158f91439
Create Date: 2021-09-18 18:23:56.681464

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '648bdf62c7e8'
down_revision = '742158f91439'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('avatar', sa.String(length=300), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'avatar')
    # ### end Alembic commands ###
